### ISSUE TITLE
Not in Maven repository yet

### ISSUE THREAD

**Issue by jottinger** [lutzhorn/dropwizard-dashboard#2]
Currently, this doesn't resolve from the main Maven repositories.

It's easily worked around; clone the repository, run `mvn install`, and all is well; from Gradle, if you have `mavenLocal()` set up as a Maven repository everything resolves properly.

This issue will go away after the repository synchronization happens, assuming the repositories sync snapshots. (If they don't, it'll go away when it hits its first real release.)

**Comment by lutzhorn** [comment]
Here we go: https://search.maven.org/#artifactdetails%7Cde.lhorn%7Cdropwizard-dashboard%7C1.0%7Cjar
