### ISSUE TITLE
With simple HTTP config, dashboard doesn't get added to the context path

### ISSUE THREAD

**Issue by jottinger** [lutzhorn/dropwizard-dashboard#3]
Project uses a single HTTP port (i.e., simple http server); following the docs ends up with HTTP startup giving this output (slightly munged to obscure project package):

```
INFO  [2017-08-18 13:04:23,875] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    POST    / (com.foo.bar.thing.http.SubmissionResource)

INFO  [2017-08-18 13:04:23,876] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@313f8301{/,null,AVAILABLE}
INFO  [2017-08-18 13:04:23,881] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)
```

`/dashboard/` obviously does nothing (gives 404s)

**Comment by lutzhorn** [comment]
As you can see in https://github.com/lutzhorn/dropwizard-dashboard/blob/ec02e6ec1644b83e2390f5e4fa251ea1864db0c2/src/main/java/de/lhorn/dropwizard/dashboard/DashboardBundle.java#L47 

the bundle just adds a Servlet to the admin context. Is this possible using the simple HTTP configuration?

**Comment by lutzhorn** [comment]
Maybe a passed `Configuration` can be used to decide which context to add to.

**Comment by lutzhorn** [comment]
Depending on the configuraiton (see #5), the Servlet is added to the admin or the application context.
